# Generated by Django 2.1.7 on 2019-04-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190331_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='length',
            field=models.CharField(default='1 Hour', max_length=255),
            preserve_default=False,
        ),
    ]
