# Generated by Django 2.1.7 on 2019-04-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190401_1203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Need',
        ),
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
