# Generated by Django 2.1.7 on 2019-04-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190407_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
