# Generated by Django 2.1.4 on 2019-01-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190102_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='_skills',
            new_name='skills_internal',
        ),
    ]
